// src/app/components/UI/Textarea.tsx
import { forwardRef, ReactNode } from "react";

interface TextareaProps {
  placeholder: string;
}

const Textarea = forwardRef(({ placeholder }: TextareaProps, ref) => {
  return <textarea className="text-black w-full rounded-md h-32 p-2" ref={ref} placeholder={placeholder}></textarea>;
});

export default Textarea;

// components/UI/Textarea.vue
<template>
  <textarea class="text-black w-full rounded-md h-32 p-2" :value="modelValue" :placeholder="placeholder" @input="emit('update:modelValue', $event.target.value)"></textarea>
</template>

<script setup lang="ts">
defineProps<{
  placeholder: string;
  modelValue: string;
}>();

const emit = defineEmits<{
  (e: "update:modelValue", payload: string);
}>();
</script>
